export const IMPORTANT_MISSING_LABS = [
  "Meta",
  "Amazon",
  "Cohere",
  "Tencent",
  "StepFun",
  "NVIDIA",
  "AI21 Labs",
];

export const RELEASES = [
  {
    model: "ChatGPT / GPT-3.5",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2022-11-30",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://openai.com/index/chatgpt/",
    notes: "Research preview met expliciet code-fix voorbeeld; startpunt voor moderne conversational coding assistants.",
  },
  {
    model: "Claude",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2023-03-14",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://www.anthropic.com/news/introducing-claude",
    notes: "Eerste brede Claude-release met coding als genoemd gebruiksscenario.",
  },
  {
    model: "GPT-4",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2023-03-14",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://openai.com/index/gpt-4-research/",
    notes: "Belangrijke sprong voor programmeer- en redeneertaken.",
  },
  {
    model: "Claude 2",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2023-07-11",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-2",
    notes: "Anthropic noemt verbeteringen in coding, math en reasoning.",
  },
  {
    model: "Qwen-7B",
    provider: "Alibaba",
    group: "Chinese+Other",
    releaseDate: "2023-08-03",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://qwenlm.github.io/blog/qwen/",
    notes: "Start van Qwen's open-source LLM-lijn.",
  },
  {
    model: "Mistral 7B",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2023-09-27",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://mistral.ai/news/announcing-mistral-7b/",
    notes: "Eerste Mistral-open model; benadert CodeLlama 7B op code volgens Mistral.",
  },
  {
    model: "GPT-4 Turbo",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2023-11-06",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/index/new-models-and-developer-products-announced-at-devday/",
    notes: "DevDay-release met Assistants API en 128K-context.",
  },
  {
    model: "Claude 2.1",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2023-11-21",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-2-1",
    notes: "200K-context, system prompts en beta tool use.",
  },
  {
    model: "Gemini 1.0",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2023-12-06",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://blog.google/technology/ai/google-gemini-ai/",
    notes: "Google's eerste Gemini-generatie; Gemini Pro API vanaf 13 december 2023.",
  },
  {
    model: "Mixtral 8x7B",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2023-12-11",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://mistral.ai/en/news/mixtral-of-experts",
    notes: "Open-weight MoE-model met sterke prijs/prestatieverhouding.",
  },
  {
    model: "GLM-4",
    provider: "Z.ai",
    group: "Chinese+Other",
    releaseDate: "2024-01-16",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://docs.z.ai/release-notes/new-released",
    notes: "Opgenomen als GLM-4-generatie; latere Z.ai notes verwijzen naar agentic/coding-capabilities in GLM-lijn.",
  },
  {
    model: "Gemini 1.5 Pro",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2024-02-15",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/technology/ai/google-gemini-next-generation-model-february-2024/",
    notes: "Doorbraak in long-context; vroege preview via AI Studio en Vertex AI.",
  },
  {
    model: "Mistral Large",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2024-02-26",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://mistral.ai/en/fr/news/mistral-large",
    notes: "Mistral noemt codegeneratie als geschikt gebruik voor dit flagship-model.",
  },
  {
    model: "Claude 3",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2024-03-04",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-3-family",
    notes: "Claude 3 Haiku, Sonnet en Opus als nieuwe model family.",
  },
  {
    model: "GPT-4o",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2024-05-13",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://openai.com/index/hello-gpt-4o/",
    notes: "Flagship multimodal model; OpenAI zegt dat het GPT-4 Turbo evenaart op Engelse tekst en code.",
  },
  {
    model: "Codestral",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2024-05-29",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://mistral.ai/fr/news/codestral",
    notes: "Mistral's eerste code-model, gericht op codegeneratie.",
  },
  {
    model: "Qwen2",
    provider: "Alibaba",
    group: "Chinese+Other",
    releaseDate: "2024-06-07",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://qwenlm.github.io/blog/qwen2/",
    notes: "Qwen noemt significant verbeterde coding- en math-prestaties.",
  },
  {
    model: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2024-06-21",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-3-5-sonnet",
    notes: "Anthropic positioneert Sonnet 3.5 als sterke coding-upgrade.",
  },
  {
    model: "DeepSeek V2.5",
    provider: "DeepSeek",
    group: "Chinese+Other",
    releaseDate: "2024-09-05",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://api-docs.deepseek.com/news/news0905/",
    notes: "Combineert DeepSeek-V2 en Coder-capabilities.",
  },
  {
    model: "OpenAI o1-preview",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2024-09-12",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/index/introducing-openai-o1-preview/",
    notes: "Nieuwe reasoning-serie voor science, coding en math.",
  },
  {
    model: "Qwen2.5",
    provider: "Alibaba",
    group: "Chinese+Other",
    releaseDate: "2024-09-19",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://qwenlm.github.io/blog/qwen2.5/",
    notes: "Grote release met Qwen2.5-Coder en verbeterde coding-capabilities.",
  },
  {
    model: "Claude 3.5 Sonnet (computer use)",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2024-10-22",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/3-5-models-and-computer-use",
    notes: "Upgraded Sonnet 3.5 met computer use in public beta.",
  },
  {
    model: "Gemini 2.0 Flash",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2024-12-11",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/technology/google-deepmind/google-gemini-ai-update-december-2024/",
    notes: "Google positioneert Gemini 2.0 als model voor de agentic era.",
  },
  {
    model: "DeepSeek V3",
    provider: "DeepSeek",
    group: "Chinese+Other",
    releaseDate: "2024-12-26",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://api-docs.deepseek.com/news/news1226",
    notes: "Open-source MoE-model dat DeepSeek met frontier gesloten modellen vergelijkt.",
  },
  {
    model: "MiniMax-01",
    provider: "MiniMax",
    group: "Chinese+Other",
    releaseDate: "2025-01-15",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.minimax.io/news/minimax-01-series-2",
    notes: "MiniMax noemt de release expliciet gericht op de AI-agent era.",
  },
  {
    model: "DeepSeek R1",
    provider: "DeepSeek",
    group: "Chinese+Other",
    releaseDate: "2025-01-20",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://api-docs.deepseek.com/news/news250120",
    notes: "Reasoningmodel met math, code en reasoning-prestaties op OpenAI-o1-niveau volgens DeepSeek.",
  },
  {
    model: "Claude 3.7 Sonnet",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2025-02-24",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-3-7-sonnet",
    notes: "Hybrid reasoning en Claude Code research preview.",
  },
  {
    model: "Gemini 2.5 Pro Preview",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2025-03-25",
    codingIndex: 46.7,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/technology/google-deepmind/google-gemini-updates-io-2025/",
    notes: "Google verwijst naar de maart-aankondiging; AA-score beschikbaar.",
  },
  {
    model: "o3",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2025-04-16",
    codingIndex: 38.4,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/o1/",
    notes: "AA-score voor reasoningmodel; maker-hub gebruikt als OpenAI-bron.",
  },
  {
    model: "Mistral Medium 3",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2025-05-07",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://mistral.ai/news/",
    notes: "Release opgenomen; geen AA Coding Index-score gevonden in de geraadpleegde top-ranglijsten.",
  },
  {
    model: "Claude Opus 4 / Sonnet 4",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2025-05-22",
    codingIndex: 34.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-4",
    notes: "Anthropic zet Claude 4 neer als coding- en agentic-sprong; score is Sonnet 4 AA-score.",
  },
  {
    model: "Kimi K2",
    provider: "Moonshot.ai",
    group: "Chinese+Other",
    releaseDate: "2025-07-11",
    codingIndex: 47.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://platform.moonshot.ai/blog/posts/changelog",
    notes: "Kimi K2-preview officieel vrijgegeven volgens Moonshot changelog; score is Kimi K2.6 AA-scorefamilie.",
  },
  {
    model: "GLM-4.5",
    provider: "Z.ai",
    group: "Chinese+Other",
    releaseDate: "2025-07-28",
    codingIndex: 44.2,
    focus: ["agentic", "programming"],
    sourceUrl: "https://z.ai/blog/glm-4.5",
    notes: "Z.ai noemt reasoning, coding en agentic abilities; AA-scorefamilie voor GLM-5/4.5-lijn.",
  },
  {
    model: "GPT-5",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2025-08-07",
    codingIndex: 38.9,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/index/",
    notes: "AA-score voor medium reasoning-profiel.",
  },
  {
    model: "Claude Sonnet 4.5",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2025-09-29",
    codingIndex: 38.6,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/claude/sonnet",
    notes: "Anthropic noemt Sonnet 4.5 het beste model voor agents, coding en computer use.",
  },
  {
    model: "GPT-5.1",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2025-11-12",
    codingIndex: 44.7,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/index/",
    notes: "AA-score voor high reasoning-profiel.",
  },
  {
    model: "Gemini 3 Pro Preview",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2025-11-18",
    codingIndex: 46.5,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/technology/google-deepmind/",
    notes: "AA-score voor high reasoning-profiel.",
  },
  {
    model: "Gemini 3.1 Pro Preview",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2025-11-18",
    codingIndex: 55.5,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/technology/google-deepmind/",
    notes: "Topscore voor Google in de geraadpleegde AA Coding Index-snapshot.",
  },
  {
    model: "Claude Opus 4.5",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2025-11-24",
    codingIndex: 47.8,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-opus-4-5",
    notes: "Gebruikt als drempel: vanaf hier is coding goed genoeg.",
  },
  {
    model: "DeepSeek V3.2 Speciale",
    provider: "DeepSeek",
    group: "Chinese+Other",
    releaseDate: "2025-12-01",
    codingIndex: 37.9,
    focus: ["agentic", "programming"],
    sourceUrl: "https://api-docs.deepseek.com/news/news251201",
    notes: "DeepSeek noemt V3.2 reasoning-first modellen built for agents.",
  },
  {
    model: "Kimi K2.5",
    provider: "Moonshot.ai",
    group: "Chinese+Other",
    releaseDate: "2025-12-16",
    codingIndex: 39.6,
    focus: ["agentic", "programming"],
    sourceUrl: "https://platform.moonshot.ai/blog/posts/changelog",
    notes: "AA-score voor reasoning-profiel.",
  },
  {
    model: "Claude Opus 4.6",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2026-02-17",
    codingIndex: 48.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news",
    notes: "Boven de Opus 4.5-drempel.",
  },
  {
    model: "Grok 4.20",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2026-03-09",
    codingIndex: 42.2,
    focus: ["agentic", "programming"],
    sourceUrl: "https://x.ai/",
    notes: "Niet in je oorspronkelijke lijst, wel impactvol voor agentic/coding tracking.",
  },
  {
    model: "MiMo-V2.5-Pro",
    provider: "Xiaomi",
    group: "Chinese+Other",
    releaseDate: "2026-03-27",
    codingIndex: 45.5,
    focus: ["agentic", "programming"],
    sourceUrl: "https://mimo.mi.com/",
    notes: "Xiaomi noemt ultimate agent performance voor V2.5 Pro.",
  },
  {
    model: "GPT-5.4",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2026-04-07",
    codingIndex: 57.2,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/index/",
    notes: "AA Coding Index topmodel in oudere snapshots.",
  },
  {
    model: "GPT-5.5",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2026-04-23",
    codingIndex: 59.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/index/",
    notes: "Hoogste AA Coding Index-score in de geraadpleegde snapshot.",
  },
  {
    model: "MiniMax-M2.7",
    provider: "MiniMax",
    group: "Chinese+Other",
    releaseDate: "2026-05-06",
    codingIndex: 41.9,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.minimax.io/news/minimax-global-announces-full-year-2025-financial-results",
    notes: "MiniMax beschrijft M2-lijn met coding, tool use en deep search.",
  },
  {
    model: "GLM-5.1",
    provider: "Z.ai",
    group: "Chinese+Other",
    releaseDate: "2026-05-12",
    codingIndex: 43.4,
    focus: ["agentic", "programming"],
    sourceUrl: "https://docs.z.ai/release-notes/new-released",
    notes: "AA-score voor reasoning-profiel.",
  },
  {
    model: "Qwen3.7 Max",
    provider: "Alibaba",
    group: "Chinese+Other",
    releaseDate: "2026-05-19",
    codingIndex: 50.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://qwenlm.github.io/blog/",
    notes: "Alibaba-model boven de Opus 4.5-drempel.",
  },
  {
    model: "Claude Opus 4.7",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2026-05-28",
    codingIndex: 53.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news",
    notes: "Boven de Opus 4.5-drempel.",
  },
  {
    model: "DeepSeek V4 Pro",
    provider: "DeepSeek",
    group: "Chinese+Other",
    releaseDate: "2026-05-30",
    codingIndex: 47.5,
    focus: ["agentic", "programming"],
    sourceUrl: "https://api-docs.deepseek.com/news/",
    notes: "Vrijwel op de Opus 4.5-drempel; afgerond nog net eronder.",
  },
  {
    model: "Kimi K2.6",
    provider: "Moonshot.ai",
    group: "Chinese+Other",
    releaseDate: "2026-05-31",
    codingIndex: 47.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://platform.moonshot.ai/blog/posts/changelog",
    notes: "Sterke Kimi-score, net onder de Opus 4.5-drempel.",
  },
  {
    model: "Claude Opus 4.8",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2026-05-31",
    codingIndex: 56.7,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news",
    notes: "Tweede frontierniveau achter GPT-5.5 in de geraadpleegde ranking.",
  },
];

export const DATA_SOURCES = [
  {
    label: "Artificial Analysis Coding Index",
    url: "https://artificialanalysis.ai/models/capabilities/coding",
  },
  {
    label: "Easy Benchmarks AA Coding Index snapshot",
    url: "https://easy-benchmarks.com/benchmarks/artificial_analysis_coding_index",
  },
  {
    label: "Megadose AA Coding Index",
    url: "https://megadose.ai/b/aa-coding-index",
  },
  {
    label: "Maker release pages",
    url: "https://openai.com/index/",
  },
];
