const aaCodingSource = "https://easy-benchmarks.com/benchmarks/artificial_analysis_coding_index";

function release(row) {
  return {
    releaseCategory: "base",
    sourceType: "official",
    ...row,
  };
}

export const IMPORTANT_MISSING_LABS = [
  "Meta",
  "Amazon",
  "Cohere",
  "Tencent",
  "StepFun",
  "NVIDIA",
  "AI21 Labs",
];

export const RELEASES = [
  release({
    model: "ChatGPT / GPT-3.5",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2022-11-30",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://openai.com/index/chatgpt/",
    notes: "First broad ChatGPT/GPT-3.5 release relevant to conversational programming workflows.",
  }),
  release({
    model: "GPT-4",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2023-03-14",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://openai.com/index/gpt-4-research/",
    notes: "Major OpenAI generation jump for reasoning and code tasks.",
  }),
  release({
    model: "Claude",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2023-03-14",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://www.anthropic.com/news/introducing-claude",
    notes: "First broad Claude release with coding listed as a use case.",
  }),
  release({
    model: "Claude 2",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2023-07-11",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-2",
    notes: "Anthropic reported improvements in coding, math, and reasoning.",
  }),
  release({
    model: "Qwen",
    provider: "Alibaba",
    group: "Chinese+Other",
    releaseDate: "2023-08-03",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://qwenlm.github.io/blog/qwen/",
    notes: "Qwen family launch; size variants are intentionally collapsed into one row.",
  }),
  release({
    model: "Mistral 7B",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2023-09-27",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://mistral.ai/news/announcing-mistral-7b/",
    notes: "Original Mistral model release; included as the base Mistral line despite the size in its official name.",
  }),
  release({
    model: "Grok 1",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2023-11-03",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://x.ai/news/grok",
    notes: "First Grok frontier LLM release; Grok-0 prototype is not tracked separately.",
  }),
  release({
    model: "GPT-4 Turbo",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2023-11-06",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/index/new-models-and-developer-products-announced-at-devday/",
    notes: "DevDay model release with Assistants API and larger context.",
  }),
  release({
    model: "Claude 2.1",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2023-11-21",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-2-1",
    notes: "200K context, system prompts, and beta tool use.",
  }),
  release({
    model: "Gemini 1.0",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2023-12-06",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://blog.google/technology/ai/google-gemini-ai/",
    notes: "First Gemini generation.",
  }),
  release({
    model: "Mixtral",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2023-12-11",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://mistral.ai/en/news/mixtral-of-experts",
    notes: "Mixtral MoE family release; parameter variants are collapsed.",
  }),
  release({
    model: "GLM-4",
    provider: "Z.ai",
    group: "Chinese+Other",
    releaseDate: "2024-01-16",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://docs.z.ai/release-notes/new-released",
    notes: "GLM generation included as the predecessor to Z.ai's later agentic GLM line.",
  }),
  release({
    model: "Gemini 1.5 Pro",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2024-02-15",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/technology/ai/google-gemini-next-generation-model-february-2024/",
    notes: "Long-context Gemini generation.",
  }),
  release({
    model: "Mistral Large",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2024-02-26",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://mistral.ai/en/fr/news/mistral-large",
    notes: "Mistral flagship general-purpose line.",
  }),
  release({
    model: "Claude 3",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2024-03-04",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-3-family",
    notes: "Claude 3 family release; Haiku/Sonnet/Opus variants are collapsed.",
  }),
  release({
    model: "Grok 1.5",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2024-03-28",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://x.ai/news/grok-1.5",
    notes: "Long-context Grok generation with improved coding and reasoning benchmarks.",
  }),
  release({
    model: "GPT-4o",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2024-05-13",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://openai.com/index/hello-gpt-4o/",
    notes: "Flagship multimodal GPT line that OpenAI said matched GPT-4 Turbo on code.",
  }),
  release({
    model: "Gemini 1.5 Flash",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2024-05-14",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/technology/ai/google-gemini-update-flash-ai-assistant-io-2024/",
    notes: "Separate speed-optimized Gemini tier, tracked independently from Gemini 1.5 Pro.",
  }),
  release({
    model: "Codestral",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2024-05-29",
    codingIndex: null,
    focus: ["programming"],
    releaseCategory: "specialized-base",
    sourceUrl: "https://mistral.ai/fr/news/codestral",
    notes: "Distinct Mistral code model line.",
  }),
  release({
    model: "Qwen2",
    provider: "Alibaba",
    group: "Chinese+Other",
    releaseDate: "2024-06-07",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://qwenlm.github.io/blog/qwen2/",
    notes: "Qwen2 family release; sizes are collapsed.",
  }),
  release({
    model: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2024-06-21",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-3-5-sonnet",
    notes: "Distinct Sonnet model line with a major coding upgrade.",
  }),
  release({
    model: "Grok 2",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2024-08-13",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://x.ai/news/grok-2",
    notes: "Grok-2 base release; Grok-2 mini is not tracked as a standalone row.",
  }),
  release({
    model: "DeepSeek V2.5",
    provider: "DeepSeek",
    group: "Chinese+Other",
    releaseDate: "2024-09-05",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://api-docs.deepseek.com/news/news0905/",
    notes: "Combined DeepSeek V2 and Coder capabilities.",
  }),
  release({
    model: "o1",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2024-09-12",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/index/introducing-openai-o1-preview/",
    notes: "Reasoning model line; preview wording is intentionally normalized out of the model name.",
  }),
  release({
    model: "Qwen2.5",
    provider: "Alibaba",
    group: "Chinese+Other",
    releaseDate: "2024-09-19",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://qwenlm.github.io/blog/qwen2.5/",
    notes: "Qwen2.5 family release; sizes are collapsed.",
  }),
  release({
    model: "Claude 3.5 Sonnet computer use",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2024-10-22",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/3-5-models-and-computer-use",
    notes: "Computer-use upgrade for the Sonnet line, relevant to agents.",
  }),
  release({
    model: "Qwen2.5-Coder",
    provider: "Alibaba",
    group: "Chinese+Other",
    releaseDate: "2024-11-12",
    codingIndex: null,
    focus: ["programming"],
    releaseCategory: "specialized-base",
    sourceUrl: "https://qwenlm.github.io/blog/qwen2.5-coder-family/",
    notes: "Distinct Qwen coding line; individual sizes are not tracked.",
  }),
  release({
    model: "Gemini 2.0 Flash",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2024-12-11",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/technology/google-deepmind/google-gemini-ai-update-december-2024/",
    notes: "First Gemini 2.0 model; Flash is tracked as its own tier instead of collapsed into the family name.",
  }),
  release({
    model: "DeepSeek V3",
    provider: "DeepSeek",
    group: "Chinese+Other",
    releaseDate: "2024-12-26",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://api-docs.deepseek.com/news/news1226",
    notes: "DeepSeek V3 family release.",
  }),
  release({
    model: "MiniMax-01",
    provider: "MiniMax",
    group: "Chinese+Other",
    releaseDate: "2025-01-15",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.minimax.io/news/minimax-01-series-2",
    notes: "MiniMax foundation model line with long context.",
  }),
  release({
    model: "DeepSeek R1",
    provider: "DeepSeek",
    group: "Chinese+Other",
    releaseDate: "2025-01-20",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://api-docs.deepseek.com/news/news250120",
    notes: "DeepSeek reasoning model line.",
  }),
  release({
    model: "Grok 3",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2025-02-19",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://x.ai/news/grok-3",
    notes: "Grok 3 base generation for reasoning agents; mini and Think mode rows are not tracked separately.",
  }),
  release({
    model: "Claude 3.7 Sonnet",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2025-02-24",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-3-7-sonnet",
    notes: "Hybrid reasoning Sonnet line and Claude Code research preview.",
  }),
  release({
    model: "Gemini 2.5 Pro",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2025-03-25",
    codingIndex: 46.7,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/technology/google-deepmind/google-gemini-updates-io-2025/",
    scoreSourceUrl: aaCodingSource,
    notes: "Gemini 2.5 Pro row normalized from preview naming; AA Coding Index score available.",
  }),
  release({
    model: "o3",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2025-04-16",
    codingIndex: 38.4,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/o1/",
    scoreSourceUrl: aaCodingSource,
    notes: "OpenAI reasoning model; AA Coding Index score available.",
  }),
  release({
    model: "Qwen3",
    provider: "Alibaba",
    group: "Chinese+Other",
    releaseDate: "2025-04-29",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://qwenlm.github.io/blog/qwen3/",
    notes: "Qwen3 family release; sizes are collapsed.",
  }),
  release({
    model: "Gemini 2.5 Flash",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2025-05-20",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/technology/google-deepmind/google-gemini-updates-io-2025/",
    notes: "Separate Flash tier for Gemini 2.5, tracked independently from Gemini 2.5 Pro.",
  }),
  release({
    model: "Mistral Medium 3",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2025-05-07",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://mistral.ai/news/mistral-medium-3",
    notes: "Mistral Medium 3 general model release with coding and STEM emphasis.",
  }),
  release({
    model: "Devstral",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2025-05-21",
    codingIndex: null,
    focus: ["agentic", "programming"],
    releaseCategory: "specialized-base",
    sourceUrl: "https://mistral.ai/news/devstral",
    notes: "Distinct Mistral software-engineering agent model line.",
  }),
  release({
    model: "Claude 4",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2025-05-22",
    codingIndex: 34.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-4",
    scoreSourceUrl: aaCodingSource,
    notes: "Claude 4 family release; Opus and Sonnet variants are collapsed for the family row.",
  }),
  release({
    model: "Magistral",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2025-06-10",
    codingIndex: null,
    focus: ["agentic", "programming"],
    releaseCategory: "specialized-base",
    sourceUrl: "https://mistral.ai/news/magistral/",
    notes: "Mistral reasoning model line; Small/Medium variants are collapsed.",
  }),
  release({
    model: "Kimi K2",
    provider: "Moonshot.ai",
    group: "Chinese+Other",
    releaseDate: "2025-07-11",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://platform.moonshot.ai/blog/posts/changelog",
    notes: "Kimi K2 model line initial release.",
  }),
  release({
    model: "Devstral Medium",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2025-07-10",
    codingIndex: null,
    focus: ["agentic", "programming"],
    releaseCategory: "specialized-base",
    sourceUrl: "https://mistral.ai/de/news/devstral-2507",
    notes: "Devstral Medium introduced as the stronger code-agent base line; Small variant is not tracked.",
  }),
  release({
    model: "Grok 4",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2025-07-09",
    codingIndex: 40.5,
    focus: ["agentic", "programming"],
    sourceUrl: "https://x.ai/news/grok-4",
    scoreSourceUrl: aaCodingSource,
    notes: "Grok 4 flagship release with native tool use; Heavy is treated as a mode/tier, not a separate base row.",
  }),
  release({
    model: "GLM-4.5",
    provider: "Z.ai",
    group: "Chinese+Other",
    releaseDate: "2025-07-28",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://z.ai/blog/glm-4.5",
    notes: "Z.ai agentic, reasoning, and coding foundation model; Air/X/Flash variants are collapsed.",
  }),
  release({
    model: "GPT-5",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2025-08-07",
    codingIndex: 38.9,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/index/",
    scoreSourceUrl: aaCodingSource,
    notes: "OpenAI GPT-5 family release; AA Coding Index score available.",
  }),
  release({
    model: "DeepSeek V3.1",
    provider: "DeepSeek",
    group: "Chinese+Other",
    releaseDate: "2025-08-21",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://api-docs.deepseek.com/news/news250821",
    notes: "DeepSeek's first step toward the agent era.",
  }),
  release({
    model: "Grok Code Fast 1",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2025-08-28",
    codingIndex: null,
    focus: ["agentic", "programming"],
    releaseCategory: "specialized-base",
    sourceUrl: "https://x.ai/news/grok-code-fast-1",
    notes: "Distinct xAI coding model built from scratch for agentic coding workflows.",
  }),
  release({
    model: "Grok 4 Fast",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2025-09-19",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://x.ai/news/grok-4-fast",
    notes: "Separate cost-efficient Grok 4 tier with native tool use and agentic search.",
  }),
  release({
    model: "Claude Sonnet 4.5",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2025-09-29",
    codingIndex: 38.6,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/claude/sonnet",
    scoreSourceUrl: aaCodingSource,
    notes: "Distinct Sonnet release for agents, coding, and computer use.",
  }),
  release({
    model: "MiniMax M2",
    provider: "MiniMax",
    group: "Chinese+Other",
    releaseDate: "2025-10-27",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.minimax.io/blog/minimax-m2-en-1748600000",
    notes: "MiniMax model born for agents and code.",
  }),
  release({
    model: "Kimi K2 Thinking",
    provider: "Moonshot.ai",
    group: "Chinese+Other",
    releaseDate: "2025-11-06",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://platform.moonshot.ai/blog/posts/changelog",
    notes: "Distinct thinking model line for complex reasoning and multi-step tool calls.",
  }),
  release({
    model: "GPT-5.1",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2025-11-12",
    codingIndex: 44.7,
    focus: ["agentic", "programming"],
    sourceUrl: "https://help.openai.com/en/articles/6825453-chatgpt-release-notes",
    scoreSourceUrl: aaCodingSource,
    notes: "OpenAI GPT-5.1 family release; AA Coding Index score available.",
  }),
  release({
    model: "Grok 4.1",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2025-11-17",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://data.x.ai/2025-11-17-grok-4-1-model-card.pdf",
    notes: "Grok 4.1 model-card date; Thinking and Non-Thinking configurations are not tracked separately.",
  }),
  release({
    model: "Gemini 3 Pro",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2025-11-18",
    codingIndex: 46.5,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/products-and-platforms/products/gemini/gemini-3-collection/",
    scoreSourceUrl: aaCodingSource,
    notes: "Flagship Gemini 3 tier, tracked independently from Gemini 3 Flash.",
  }),
  release({
    model: "Gemini 3 Flash",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2025-12-17",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/products/gemini/gemini-3-flash/",
    notes: "Separate speed-optimized Gemini 3 tier for agentic workflows.",
  }),
  release({
    model: "Claude Opus 4.5",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2025-11-24",
    codingIndex: 47.8,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-opus-4-5",
    scoreSourceUrl: aaCodingSource,
    notes: "Opus 4.5 is the coding-solved threshold row.",
  }),
  release({
    model: "Grok 4.1 Fast",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2025-11-19",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://x.ai/news/grok-4-1-fast",
    notes: "Separate fast tool-calling model line; reasoning and non-reasoning API variants are collapsed.",
  }),
  release({
    model: "DeepSeek V3.2",
    provider: "DeepSeek",
    group: "Chinese+Other",
    releaseDate: "2025-12-01",
    codingIndex: 36.7,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.deepseek.com/en/transparency/",
    scoreSourceUrl: aaCodingSource,
    notes: "DeepSeek V3.2 base release; Speciale score rows are not tracked separately.",
  }),
  release({
    model: "Mistral Large 3",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2025-12-02",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://mistral.ai/fr/news/mistral-3",
    notes: "Mistral 3 family represented by Large 3; smaller Ministral variants are not tracked.",
  }),
  release({
    model: "Devstral 2",
    provider: "Mistral",
    group: "Chinese+Other",
    releaseDate: "2025-12-09",
    codingIndex: null,
    focus: ["agentic", "programming"],
    releaseCategory: "specialized-base",
    sourceUrl: "https://mistral.ai/fr/news/devstral-2-vibe-cli/",
    notes: "Next-generation Mistral code-agent line; Small variant is not tracked.",
  }),
  release({
    model: "GPT-5.2",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2025-12-11",
    codingIndex: 48.7,
    focus: ["agentic", "programming"],
    sourceUrl: "https://platform.openai.com/docs/models/gpt-5.2/",
    scoreSourceUrl: aaCodingSource,
    notes: "OpenAI flagship model for coding and agentic tasks.",
  }),
  release({
    model: "Kimi K2.5",
    provider: "Moonshot.ai",
    group: "Chinese+Other",
    releaseDate: "2026-01-27",
    codingIndex: 39.6,
    focus: ["agentic", "programming"],
    sourceUrl: "https://platform.moonshot.ai/docs/guide/agent-support.en-US",
    scoreSourceUrl: aaCodingSource,
    notes: "Kimi K2.5 model line; turbo variants are not tracked.",
  }),
  release({
    model: "Claude Opus 4.6",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2026-02-05",
    codingIndex: 48.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-opus-4-6",
    scoreSourceUrl: aaCodingSource,
    notes: "Released the same day as GPT-5.3-Codex; strong coding and agentic upgrade.",
  }),
  release({
    model: "GPT-5.3-Codex",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2026-02-05",
    codingIndex: 53.1,
    focus: ["agentic", "programming"],
    releaseCategory: "specialized-base",
    sourceUrl: "https://openai.com/index/introducing-gpt-5-3-codex",
    scoreSourceUrl: aaCodingSource,
    notes: "Distinct Codex model line for agentic coding; Spark variant is not tracked.",
  }),
  release({
    model: "MiniMax M2.5",
    provider: "MiniMax",
    group: "Chinese+Other",
    releaseDate: "2026-02-12",
    codingIndex: 37.4,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.minimax.io/news/minimax-m25",
    scoreSourceUrl: aaCodingSource,
    notes: "MiniMax M2.5 agentic coding model line.",
  }),
  release({
    model: "GLM-5",
    provider: "Z.ai",
    group: "Chinese+Other",
    releaseDate: "2026-02-12",
    codingIndex: 44.2,
    focus: ["agentic", "programming"],
    sourceUrl: "https://z.ai/blog/glm-5",
    scoreSourceUrl: aaCodingSource,
    notes: "Z.ai GLM-5 model for complex systems engineering and long-horizon agents.",
  }),
  release({
    model: "Claude Sonnet 4.6",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2026-02-17",
    codingIndex: 50.9,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-sonnet-4-6",
    scoreSourceUrl: aaCodingSource,
    notes: "Distinct Sonnet release for coding, computer use, and agent planning.",
  }),
  release({
    model: "Grok 4.20",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2026-03-10",
    codingIndex: 42.2,
    focus: ["agentic", "programming"],
    sourceUrl: "https://docs.x.ai/docs/release-notes",
    scoreSourceUrl: aaCodingSource,
    notes: "xAI release-note date for Grok 4.20 availability.",
  }),
  release({
    model: "MiniMax M2.7",
    provider: "MiniMax",
    group: "Chinese+Other",
    releaseDate: "2026-03-18",
    codingIndex: 41.9,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.minimax.io/blog/minimax-m27",
    scoreSourceUrl: aaCodingSource,
    notes: "MiniMax M2.7 self-evolution model line.",
  }),
  release({
    model: "GPT-5.4",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2026-03-05",
    codingIndex: 57.2,
    focus: ["agentic", "programming"],
    sourceUrl: "https://help.openai.com/en/articles/6825453-chatgpt-release-notes",
    scoreSourceUrl: aaCodingSource,
    notes: "OpenAI GPT-5.4 Thinking release; mini/nano variants are not tracked.",
  }),
  release({
    model: "GLM-5.1",
    provider: "Z.ai",
    group: "Chinese+Other",
    releaseDate: "2026-04-07",
    codingIndex: 43.4,
    focus: ["agentic", "programming"],
    sourceUrl: "https://docs.z.ai/release-notes/new-released",
    scoreSourceUrl: aaCodingSource,
    notes: "Z.ai GLM-5.1 long-horizon engineering model.",
  }),
  release({
    model: "Claude Opus 4.7",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2026-04-16",
    codingIndex: 53.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-opus-4-7",
    scoreSourceUrl: aaCodingSource,
    notes: "Opus 4.7 release for stronger coding and multi-step work.",
  }),
  release({
    model: "Kimi K2.6",
    provider: "Moonshot.ai",
    group: "Chinese+Other",
    releaseDate: "2026-04-21",
    codingIndex: 47.1,
    focus: ["agentic", "programming"],
    sourceType: "secondary",
    sourceUrl: "https://forum.moonshot.ai/c/announcement/5",
    scoreSourceUrl: aaCodingSource,
    notes: "Kimi K2.6 release date from Kimi announcement index; AA score available.",
  }),
  release({
    model: "MiMo-V2.5-Pro",
    provider: "Xiaomi",
    group: "Chinese+Other",
    releaseDate: "2026-04-22",
    codingIndex: 45.5,
    focus: ["agentic", "programming"],
    sourceType: "secondary",
    sourceUrl: "https://www.llmreference.com/provider/xiaomi/mimo-v2-5-pro",
    scoreSourceUrl: aaCodingSource,
    notes: "Xiaomi coding/agentic flagship; non-Pro and modality variants are not tracked.",
  }),
  release({
    model: "GPT-5.5",
    provider: "OpenAI",
    group: "Frontier labs",
    releaseDate: "2026-04-23",
    codingIndex: 59.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://openai.com/index/introducing-gpt-5-5/",
    scoreSourceUrl: aaCodingSource,
    notes: "OpenAI GPT-5.5 release; Pro/Instant variants are not tracked.",
  }),
  release({
    model: "DeepSeek V4",
    provider: "DeepSeek",
    group: "Chinese+Other",
    releaseDate: "2026-04-24",
    codingIndex: 47.5,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.deepseek.com/en/transparency/",
    scoreSourceUrl: aaCodingSource,
    notes: "DeepSeek V4 base family release; AA score uses the top V4 Pro coding row.",
  }),
  release({
    model: "Grok 4.3",
    provider: "xAI",
    group: "Chinese+Other",
    releaseDate: "2026-04-30",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceType: "secondary",
    sourceUrl: "https://docs.x.ai/developers/models/grok-4.3",
    notes: "Official xAI model page confirms Grok 4.3; release date is from secondary reporting because no dated xAI news post was found.",
  }),
  release({
    model: "Qwen3.7-Max",
    provider: "Alibaba",
    group: "Chinese+Other",
    releaseDate: "2026-05-19",
    codingIndex: 50.1,
    focus: ["agentic", "programming"],
    sourceType: "secondary",
    sourceUrl: "https://news.aibase.com/news/28282",
    scoreSourceUrl: aaCodingSource,
    notes: "Qwen3.7-Max release reported from Alibaba Qwen's official WeChat announcement; Plus and preview variants are not tracked.",
  }),
  release({
    model: "Gemini 3.5 Flash",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2026-05-19",
    codingIndex: 47.1,
    focus: ["agentic", "programming"],
    sourceUrl: "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-5/",
    scoreSourceUrl: aaCodingSource,
    notes: "First public Gemini 3.5 tier; Pro was announced for a later June 2026 release and is not tracked until released.",
  }),
  release({
    model: "Claude Opus 4.8",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2026-05-28",
    codingIndex: 56.7,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-opus-4-8",
    scoreSourceUrl: aaCodingSource,
    notes: "Latest Opus release in the verified dataset.",
  }),
  release({
    model: "MiniMax M3",
    provider: "MiniMax",
    group: "Chinese+Other",
    releaseDate: "2026-06-01",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.minimax.io/blog/minimax-m3",
    notes: "Official MiniMax M3 release for frontier coding, agentic work, 1M context, and native multimodality; AA score not available in the consulted snapshot.",
  }),
  release({
    model: "Composer 2.5",
    provider: "Cursor",
    group: "Chinese+Other",
    releaseDate: "2026-06-11",
    codingIndex: null,
    focus: ["agentic", "programming"],
    releaseCategory: "specialized-base",
    sourceUrl: "https://cursor.com/blog/composer-2-5",
    notes: "Cursor's Composer 2.5 coding model, built on Moonshot's Kimi K2.5 checkpoint, improves long-running tasks and complex instruction following.",
  }),
  release({
    model: "Claude Fable 5",
    provider: "Anthropic",
    group: "Frontier labs",
    releaseDate: "2026-06-09",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://www.anthropic.com/news/claude-fable-5-mythos-5",
    notes: "Mythos-class generally available Claude release for long-horizon software engineering; Mythos 5 is treated as a restricted-access variant of the same underlying model.",
  }),
  release({
    model: "DiffusionGemma",
    provider: "Google",
    group: "Frontier labs",
    releaseDate: "2026-06-10",
    codingIndex: null,
    focus: ["programming"],
    sourceUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/diffusion-gemma-faster-text-generation",
    notes: "Experimental open 26B MoE text-diffusion model for speed-critical local developer workflows such as inline editing and rapid iteration.",
  }),
  release({
    model: "Kimi K2.7 Code",
    provider: "Moonshot.ai",
    group: "Chinese+Other",
    releaseDate: "2026-06-12",
    codingIndex: null,
    focus: ["agentic", "programming"],
    releaseCategory: "specialized-base",
    sourceType: "secondary",
    sourceUrl: "https://developers.cloudflare.com/changelog/post/2026-06-12-kimi-k2-7-code-workers-ai/",
    notes: "Code-optimized Kimi K2 variant with improved coding and agentic benchmark performance over K2.6; official Moonshot social release corroborates availability.",
  }),
  release({
    model: "GLM-5.2",
    provider: "Z.ai",
    group: "Chinese+Other",
    releaseDate: "2026-06-13",
    codingIndex: null,
    focus: ["agentic", "programming"],
    sourceUrl: "https://docs.z.ai/devpack/latest-model",
    notes: "Flagship Z.ai coding model available to GLM Coding Plan users with 1M-context support; API, chatbot, and MIT open weights were announced as following the initial coding-plan rollout.",
  }),
];

export const DATA_SOURCES = [
  {
    label: "Artificial Analysis Coding Index",
    url: "https://artificialanalysis.ai/models/capabilities/coding",
  },
  {
    label: "Easy Benchmarks AA Coding Index snapshot",
    url: aaCodingSource,
  },
  {
    label: "Maker release pages",
    url: "https://openai.com/index/",
  },
];
